### ISSUE TITLE
No RSS <pubDate> tag.

### ISSUE THREAD

**Issue by Axce** [Nyrio/personal-site#1]
Unless all your articles were written on 1970, january 1st at 00:00, it seems that your RSS feed lacks a <pubDate> tag !
![image](https://user-images.githubusercontent.com/9214221/42691567-d47d993c-86a8-11e8-9f67-7cd31035b133.png)
Save my feed, save my reader, please save us all.

**Comment by Nyrio** [comment]
Hi! Thanks for reporting this issue.
It should have been solved in f25f37b2b279c9215659a67855758e6e1ee497f6, can you confirm?

**Comment by Axce** [comment]
I can confirm.
